var Language = __ial = {
     
     Client:{
     	ConfigurationManagement:"配置管理",
     	AlarmManagement:"報警管理",
     	CaseDynamicTable:"案件動態表",
     	PoliceDeploymentOnlineRate:"警力在線部署",
     	OnLineRateOfSecurityEquipment:"安防設備在線率",
     	CaseType:"案件類型",
     	ComprehensiveCaseStatistics:"綜合案例統計",
     	PoliceStatistics:"警種統計",
     	end:true
     },
     Init:{
     	ImplementationRate:"執行率",
     	PoliceForceDeployment:"警力部署",
     	Equipment:"設備",
     	ComprehensiveCase:"綜合案例",
     	end:true
     },
     loadData:{
     	AnalyCaseingUser:{
     		HaveTask:"有任務",
     		NoTask:"無任務",
     		end:true
     	},
     	AnalyDev:{
     		OnlineVehicle:"在線$車載",
     		OfflineVehicle:"離線$車載",
     		OnlineFixedPoint:"在線$固定點",
     		OfflineFixedPoint:"離線$按固定點",
     		OnlineSingleSoldier:"在線$單兵",
     		OfflineSingleSoldier:"離線$單兵",
     		OnlineUAV:"在線$無人機",
     		OfflineUAV:"離線$無人機",
     		end:true
     	},
     	AnalyCaseType:{
     		IncidenceCase:"案發率",
     		RateSettlement:"結案率",
     		end:true
     	},
     	AnalyCase:{
     		Completed:"已完成",
     		Underway:"正在進行",
     		UnCompleted:"未完成",
     		end:true
     	},
     	AnalyPoliceType:{
     		IncidenceCase:"案發率",
     		end:true
     	},
     	end:true
     },
     end:true
}