var Language = __ial = {
     
     Client:{
     	ConfigurationManagement:"配置管理",
     	AlarmManagement:"报警管理",
     	CaseDynamicTable:"案件动态表",
     	PoliceDeploymentOnlineRate:"警力部署在线率",
     	OnLineRateOfSecurityEquipment:"安防设备在线率",
     	CaseType:"案件类型",
     	ComprehensiveCaseStatistics:"综合案例统计",
     	PoliceStatistics:"警种统计",
     	end:true
     },
     Init:{
     	ImplementationRate:"执行率",
     	PoliceForceDeployment:"警力部署",
     	Equipment:"设备",
     	ComprehensiveCase:"综合案例",
     	end:true
     },
     loadData:{
     	AnalyCaseingUser:{
     		HaveTask:"有任务",
     		NoTask:"无任务",
     		end:true
     	},
     	AnalyDev:{
     		OnlineVehicle:"在线$车载",
     		OfflineVehicle:"离线$车载",
     		OnlineFixedPoint:"在线$固定点",
     		OfflineFixedPoint:"离线$固定点",
     		OnlineSingleSoldier:"在线$单兵",
     		OfflineSingleSoldier:"离线$单兵",
     		OnlineUAV:"在线$无人机",
     		OfflineUAV:"离线$无人机",
     		end:true
     	},
     	AnalyCaseType:{
     		IncidenceCase:"案发率",
     		RateSettlement:"结案率",
     		end:true
     	},
     	AnalyCase:{
     		All:"总数",
     		Completed:"已完成",
     		Underway:"正在进行",
     		UnCompleted:"未完成",
     		end:true
     	},
     	AnalyPoliceType:{
     		IncidenceCase:"案发率",
     		end:true
     	},
     	end:true
     },
     end:true
}